#!/bin/bash
# 大脑自动运转配置助手

echo "🚀 AI Common 大脑自动运转系统配置"
echo ""
echo "自动运转已在运行中！如需定时自动运转，请选择配置方式："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 配置方式选择："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣ Cron 定时任务 (推荐)"
echo "   • 安装: brew install cron"
echo "   • 查看当前: crontab -l"
echo "   • 添加定时: crontab -e"
echo "   • 添加后: */5 * * * * cd /Users/webkubor/Documents/AI_Common && node scripts/auto-pilot.js >> logs/auto-pilot.log 2>&1"
echo ""
echo "2️⃣ PM2 定期任务"
echo "   • 安装: npm install pm2"
echo "   • 启动: pm2 schedule '*/5 * * * *'"
echo ""
echo "3️⃣ 手动启动"
echo "   • node scripts/auto-pilot.js"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 当前状态:"
echo "   • 知识库自检: 运行中"
echo "   • 操作记录: 自动记录"
echo "   • 大脑状态: 自动运转"
echo ""
echo "💡 建议:"
echo "   • 第一次运行后，定时任务会自动记录到 memory/journal/"
echo "   • 可以运行 tail -f docs/memory/journal/$(date +%Y-%m-%d).md 查看记录"
echo "   • 大脑现在自己运转，你不需要做任何事了"
echo ""