#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

START_MARK="# >>> AI_COMMON_CODEX_ALIAS_START >>>"
END_MARK="# <<< AI_COMMON_CODEX_ALIAS_END <<<"

TARGET_SHELL=""
RC_FILE=""
DRY_RUN=0

usage() {
  cat <<'EOF'
用法:
  bash scripts/actions/setup-codex-alias.sh [--shell zsh|bash] [--rc-file <path>] [--dry-run]

说明:
  - 默认根据 $SHELL 自动选择 rc 文件:
    - zsh -> ~/.zshrc
    - bash -> ~/.bashrc
  - 会写入一段可重复更新的 managed block（幂等）
  - 写入后可用快捷命令:
    - codex-brain
    - cdxb "任务描述"
    - gemini-brain
    - gmb "任务描述"
    - claude-brain
    - clb "任务描述"
    - handoverc "节点ID"
    - fleetstat
    - brain-gate
EOF
}

detect_default_shell() {
  local shell_name
  shell_name="$(basename "${SHELL:-zsh}")"
  if [[ "$shell_name" == "zsh" || "$shell_name" == "bash" ]]; then
    echo "$shell_name"
  else
    echo "zsh"
  fi
}

resolve_rc_file() {
  local shell_name="$1"
  if [[ -n "$RC_FILE" ]]; then
    echo "$RC_FILE"
    return
  fi
  if [[ "$shell_name" == "bash" ]]; then
    echo "${HOME}/.bashrc"
  else
    echo "${HOME}/.zshrc"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --shell)
      TARGET_SHELL="${2:-}"
      shift 2
      ;;
    --rc-file)
      RC_FILE="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "未知参数: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$TARGET_SHELL" ]]; then
  TARGET_SHELL="$(detect_default_shell)"
fi

if [[ "$TARGET_SHELL" != "zsh" && "$TARGET_SHELL" != "bash" ]]; then
  echo "不支持的 shell: $TARGET_SHELL (仅支持 zsh/bash)"
  exit 1
fi

RC_FILE="$(resolve_rc_file "$TARGET_SHELL")"
RC_FILE="${RC_FILE/#\~/$HOME}"

mkdir -p "$(dirname "$RC_FILE")"
touch "$RC_FILE"

TMP_FILE="$(mktemp)"
cleanup() {
  rm -f "$TMP_FILE"
}
trap cleanup EXIT

awk -v start="$START_MARK" -v end="$END_MARK" '
  $0 == start { skip=1; next }
  $0 == end { skip=0; next }
  !skip { print }
' "$RC_FILE" > "$TMP_FILE"

cat >> "$TMP_FILE" <<EOF

$START_MARK
# Auto-generated by AI_Common: codex/gemini/claude brain bootstrap shortcuts
alias codex-brain="${ROOT_DIR}/scripts/actions/codex-with-fleet.sh"
alias gemini-brain="${ROOT_DIR}/scripts/actions/gemini-with-fleet.sh"
alias claude-brain="${ROOT_DIR}/scripts/actions/claude-with-fleet.sh"
alias fleetstat='cd "${ROOT_DIR}" && pnpm run fleet:status'
alias brain-gate='cd "${ROOT_DIR}" && pnpm run health:gate'

cdxb() {
  local _task="待分配任务"
  if [[ \$# -gt 0 && "\$1" != --* ]]; then
    _task="\$1"
    shift
  fi
  "${ROOT_DIR}/scripts/actions/codex-with-fleet.sh" --task "\$_task" "\$@"
}

gmb() {
  local _task="待分配任务"
  if [[ \$# -gt 0 && "\$1" != --* ]]; then
    _task="\$1"
    shift
  fi
  "${ROOT_DIR}/scripts/actions/gemini-with-fleet.sh" --task "\$_task" "\$@"
}

clb() {
  local _task="待分配任务"
  if [[ \$# -gt 0 && "\$1" != --* ]]; then
    _task="\$1"
    shift
  fi
  "${ROOT_DIR}/scripts/actions/claude-with-fleet.sh" --task "\$_task" "\$@"
}

handoverc() {
  if [[ \$# -lt 1 ]]; then
    echo '用法: handoverc "Codex-3 (Codex)" [--dry-run]'
    return 1
  fi
  local _node="\$1"
  shift
  cd "${ROOT_DIR}" && pnpm run fleet:handover -- --to-node "\$_node" "\$@"
}
$END_MARK
EOF

if [[ "$DRY_RUN" == "1" ]]; then
  echo "[dry-run] 将更新: $RC_FILE"
  echo "--------------------"
  sed -n "/^$START_MARK\$/,/^$END_MARK\$/p" "$TMP_FILE"
  echo "--------------------"
  exit 0
fi

BACKUP_FILE="${RC_FILE}.ai_common.bak.$(date +%Y%m%d%H%M%S)"
cp "$RC_FILE" "$BACKUP_FILE"
mv "$TMP_FILE" "$RC_FILE"

echo "✅ 已写入快捷配置: $RC_FILE"
echo "🗂 备份文件: $BACKUP_FILE"
echo "♻️ 让配置生效: source \"$RC_FILE\""
echo "🚀 启动 Codex 并自动入脑: cdxb \"你的任务\""
echo "🚀 启动 Claude 并自动入脑: clb \"你的任务\""
echo "👑 移交 0 号机队长: handoverc \"Codex-3 (Codex)\""
echo "📊 查看 Agent Team 状态: fleetstat"
